#Finding a set of codons from a given sequence

sequence = '''AGCCCTCCAGGACAGGCTGCATCAGAAGAGGCCATCAAGCAGGTCTGTTCCAAGGGCCTTTGCGTCAGGT
GGGCTCAGGATTCCAGGGTGGCTGGACCCCAGGCCCCAGCTCTGCAGCAGGGAGGACGTGGCTGGGCTCG
TGAAGCATGTGGGGGTGAGCCCAGGGGCCCCAAGGCAGGGCACCTGGCCTTCAGCCTGCCTCAGCCCTGC
CTGTCTCCCAGATCACTGTCCTTCTGCCATGGCCCTGTGGATGCGCCTCCTGCCCCTGCTGGCGCTGCTG
GCCCTCTGGGGACCTGACCCAGCCGCAGCCTTTGTGAACCAACACCTGTGCGGCTCACACCTGGTGGAAG
CTCTCTACCTAGTGTGCGGGGAAC'''

codon_list = ["ATG", "TAA", "TAG", "TGA", "AUG"]

cdn_position = []

seq_length = len(sequence)

i = 0

while i < seq_length - 2:
    possible_cdn = sequence[i:i+3]
    if possible_cdn in codon_list:
        cdn_position.append(i)
    i = i+1

print(f"codons are found at indices {cdn_position}") 





